TITLE NUMEROS NEGATIVOS
;@Author : Ricardo Andres Rivera Montoya
;@Country: El Salvador, Centro America
;@eMail  : 2931322018@mail.utec.edu.sv
INCLUDE IRVINE32.INC
.DATA
   NEGA1 SBYTE -3
   NORM1 BYTE 4
   NEGA2 BYTE -2
   M1 BYTE "-3 EN HEXADECIMAL ES : ",0
   M2 BYTE "-3 EN DECIMAL ES : ",0
   M3 BYTE "-2 - (4) EN DECIMAL ES : ",0
   M4 BYTE "4 - (-2) EN DECIMAL ES : ",0
.CODE
NEGA PROC
   MOV EAX,0
   MOV AL,NEGA1
   MOV EDX,OFFSET M1
   CALL WRITESTRING
   CALL DUMPREGS
   CALL CRLF
   ;
   MOV EDX,OFFSET M2
   CALL WRITESTRING
   CALL WRITEDEC
   CALL CRLF
   ;
   MOV AL,NEGA2 ; AL = -2
   SUB AL,NORM1 ; AL = AL - NORM1 ? -2 - (4)
   MOV EDX,OFFSET M3
   CALL WRITESTRING
   CALL WRITEDEC
   ;
   CALL CRLF
   MOV AL,NORM1
   SUB AL,NEGA2 ; 4 - (-2 ) IGUAL A 6 POSITIVO
   MOV EDX,OFFSET M4
   CALL WRITESTRING
   CALL WRITEDEC
   EXIT
NEGA ENDP
  END NEGA
