TITLE Vocales_Asteriscos
;@Author : Ricardo Andres Rivera Montoya
;@Country: El Salvador, Centro America
;@eMail  : 2931322018@mail.utec.edu.sv
INCLUDE IRVINE32.INC
 
.DATA 
   C1 BYTE "FACIL ES BUSCAR, FACIL NO ENCONTRAR",0
   MSJ1 BYTE "LO ENCONTRE",0
   MSJ2 BYTE "NO LO ENCONTRE",0
 
.CODE
MAIN PROC
   MOV EDI, OFFSET C1
   MOV ECX,LENGTHOF C1
   MOV AL,"A"
   REPNE SCASB 
   JE LOENCONTRE
 
   MOV EDX,OFFSET MSJ2
   CALL WRITESTRING
   JMP SALIR:
 
LOENCONTRE:
   MOV EDX,OFFSET MSJ1
   CALL WRITESTRING
 
SALIR: 
   EXIT
MAIN ENDP
     END MAIN