TITLE IFSANIDADO
;@Author : Ricardo Andres Rivera Montoya
;@Country: El Salvador, Centro America
;@eMail  : 2931322018@mail.utec.edu.sv
INCLUDE IRVINE32.INC
 
.DATA
   MSJ1 BYTE "LUNES 06 DE NOVIEMBRE",0
   L=(4-MSJ1)
   MSJ2 BYTE "LUNES 06 DW NOVIEMBRE",0
   IGUALES BYTE "SON IGUALES",0
   NOIGUALES BYTE "NO SON IGUALES",0
   POSICION BYTE "SON DIFERENTES A PARTIR DE: ",0
 
.CODE
MAIN PROC
   MOV ESI,OFFSET MSJ1
   MOV EDI, OFFSET MSJ2
   MOV ECX, L
   MOV EAX,L
   REPE CMPSB 
   CMP ECX,0
   JE SONIGUALES
   MOV EDX,OFFSET NOIGUALES
   CALL WRITESTRING
   CALL CRLF
   MOV EDX, OFFSET POSICION
   CALL WRITESTRING
   SUB EAX,ECX
   CALL WRITEDEC
   JMP SALIR
 
   SONIGUALES:
   MOV EDX,OFFSET IGUALES
   CALL WRITESTRING
   SALIR: EXIT
MAIN ENDP
     END MAIN