TITLE STOSBSTOSWSTOSD
;@Author : Ricardo Andres Rivera Montoya
;@Country: El Salvador, Centro America
;@eMail  : 2931322018@mail.utec.edu.sv
INCLUDE IRVINE32.INC
 
.DATA
   STR1 BYTE "STR1 IS STRING ONE",0
   STR2 BYTE LENGTHOF STR1 DUP(30H)
 
.CODE
MOV SBX PROC
   MOV ESI,OFFSET STR1
   MOV EDI,OFFSET STR2
   MOV ECX, LENGTHOF STR1
 
   REP MOV SB 
 
   MOV EDX,OFFSET STR2
   CALL WRITESTRING
   CALL CRLF
   EXIT
MOV SBX ENDP