TITLE INSTRUCCION ELSEIFf
 ;@Author : Ricardo Andres Rivera Montoya
;@Country: El Salvador, Centro America
;@eMail  : 2931322018@mail.utec.edu.sv
INCLUDE IRVINE32.INC
 
COMMENT /
 IF (EAX <= 3000 )
     PRINT "NO PAGA IMPUESTO"
 ELSEIF ( EAX > 3000 && EAX <= 5000)
    PRINT " PAGO ENTRE 3000 Y 5000"
 ELSEIF (EAX > 5000 && EAX <= 10000)
   PRINT "PAGA ENTRE 5000 Y 10000"
 ELSE
   PRINT "PAGA MAS DE 10000"
ENDIF
/
 
.DATA
   GANANCIA BYTE "ENTRE SU GANACIA ANUAL ",0
   TAX2 BYTE " IMPUESTO A PAGAR ES ENTRE 3000 Y 5000",0
   TAX3 BYTE " IMPUESTO A PAGAR ES 5000 Y 10000",0
   TAX4 BYTE " IMPUESTO A PAGAR ES MAS DE 10000",0
   TAX1 BYTE " IMPUESTO A PAGAR ES 0.00",0
 
.CODE
 
MAIN PROC
;Aquí vamos a llamar a dos procedimientos que no están en la biblioteca IRVINE32.inc y por tanto tengo que hacer la descripción de estos
; procedimientos definidos por el usuario, en este caso, el programador
   CALL PEDIR
   CALL PROCESO
   EXIT
MAIN ENDP
 
PEDIR PROC
   CALL CRLF
   MOV EDX, OFFSET GANANCIA
   CALL WRITESTRING
   CALL CRLF
   CALL CRLF
   CALL READDEC
   RET
PEDIR ENDP
 
;
PROCESO PROC
   CMP EAX,3000
   JA ELSE1
   CALL CRLF
 
   MOV EDX,OFFSET TAX1
   CALL WRITESTRING
   CALL CRLF
   JMP FIN
 
ELSE1: CMP EAX,3000
   JA TEST1
   JMP ELSE2
 
TEST1: CMP EAX,5000
   JA ELSE2
   CALL CRLF
   MOV EDX,OFFSET TAX2
   CALL WRITESTRING
   CALL CRLF
   JMP FIN
 
ELSE2: CMP EAX,5000
   JA TEST3
   JMP ELSE3
 
TEST3: CMP EAX,10000
   JA ELSE3
   CALL CRLF
   MOV EDX,OFFSET TAX3
   CALL WRITESTRING
   CALL CRLF
   JMP FIN
 
ELSE3: CALL CRLF
   MOV EDX,OFFSET TAX4
   CALL WRITESTRING
   CALL CRLF
 
   FIN: RET
PROCESO ENDP
END MAIN
