TITLE IFSANIDADO
;@Author : Ricardo Andres Rivera Montoya
;@Country: El Salvador, Centro America
;@eMail  : 2931322018@mail.utec.edu.sv
INCLUDE IRVINE32.INC
 
.DATA
   UNO BYTE "UNO",0
   DOS BYTE "DOS",0
   TRES BYTE "TRES",0
   ASK BYTE "ENTRE UN NUMERO (EBX) ",0
   ASK2 BYTE "ENTRE UN NUMERO (EAX) ",0
 
.CODE
IFSS PROC
   MOV EDX,OFFSET ASK
   CALL WRITESTRING
   CALL READDEC
   MOV EBX,EAX ; VALOR DE EBX
   CALL CRLF ; SALTAR LINEA
﻿
   MOV EDX,OFFSET ASK2
   CALL WRITESTRING
   CALL READDEC ; VALOR DE EAX
   CALL CRLF
 
   ; Vamos a hacer la comparación de EAX con 10 y 20 a ver si cumple el criterio
   CMP EAX,10
   JBE ELSEX
   CMP EAX,20
   JA ELSEX
   MOV EDX,OFFSET UNO
   CALL WRITESTRING
   CALL CRLF
 
   ; AHORA COMPARO EBX PARA VER SI CUMPLE LOS CRITERIOS
   CMP EBX,10
   JBE FUERA
   CMP EBX,20
   JA FUERA
   MOV EDX,OFFSET DOS
   CALL WRITESTRING
   CALL CRLF
   CALL WAITMSG
   JMP FUERA
﻿
   ELSEX: MOV EDX,OFFSET TRES
   CALL WRITESTRING
   CALL CRLF
 
   FUERA: EXIT
IFSS ENDP
     END IFSS