TITLE Resta
;@Author : Ricardo Andres Rivera Montoya
;@Country: El Salvador, Centro America
;@eMail  : 2931322018@mail.utec.edu.sv
INCLUDE Irvine32.inc

.DATA
MSG BYTE "Ingrese un numero: ",0
MSG2 BYTE "El resultado es positivo: ",0
MSG3 BYTE "El resultado es negativo: ",0
NUMERO1 DWORD 0

MOSTRARMENSAJE TEXTEQU <CALL WRITESTRING>
CAPTURAR TEXTEQU <CALL READDEC>
MOVER TEXTEQU <MOV>
RESTAR TEXTEQU <SUB>
ASIGNARMENSAJE TEXTEQU <OFFSET>
MOSTRARDECIMAL TEXTEQU <CALL WRITEINT>
FIN EQU <EXIT>

.CODE
MR PROC
MOV EDX, ASIGNARMENSAJE MSG
MOSTRARMENSAJE
CAPTURAR
MOV NUMERO1, EAX

MOSTRARMENSAJE
CAPTURAR

RESTAR NUMERO1, EAX
MOV EAX, NUMERO1

.IF EAX > 0
MOV EDX, ASIGNARMENSAJE MSG2
MOSTRARMENSAJE
MOSTRARDECIMAL
.ELSE
MOV EDX, ASIGNARMENSAJE MSG3
MOSTRARMENSAJE
MOSTRARDECIMAL
.ENDIF

FIN
MR ENDP
END MR