TITLE usoLoop
;@Author : Ricardo Andres Rivera Montoya
;@Country: El Salvador, Centro America
;@eMail  : 2931322018@mail.utec.edu.sv
INCLUDE IRVINE32.INC
.DATA
MSG BYTE "INGRESE UN NUMERO: ",0
MSG2 BYTE "LA SUMA TOTAL: ",0

.CODE
MR PROC

MOV EDX, OFFSET MSG
MOV EBX, 0
MOV ECX, 10

SUMA:
    CALL WRITESTRING
    CALL READINT
    ADD EBX, EAX
    LOOP SUMA

MOV EDX, OFFSET MSG2
CALL WRITESTRING
MOV EAX, EBX
CALL WRITEDEC

EXIT
MR ENDP
END MR
