TITLE VOCALES
INCLUDE IRVINE32.INC
 
.DATA
   LA BYTE "LETRA A",0
   LE1 BYTE "LETRA E",0
   LI BYTE "LETRA I",0
   LO BYTE "LETRA O",0
   LU BYTE "LETRA U",0
   PEDIR BYTE " ENTRE UN CARACTER ASCCII >>> ",0
   NADA BYTE "NO ES VOCAL O ENTRO UNA VOCAL EN MINUSCULA "
 
.CODE
VOCAL PROC
   MOV EDX,OFFSET PEDIR
   CALL WRITESTRING
   CALL READCHAR
   CALL CRLF
 
   CMP AL,"A"
   JE LA1
 
   CMP AL, "E"
   JE LE2
 
   CMP AL,"I"
   JE LI1
 
   CMP AL,"O"
   JE LO1
 
   CMP AL,"U"
   JE LU1
 
   MOV EDX,OFFSET NADA
   CALL CRLF
   CALL WRITESTRING
   JMP FIN
 
   LA1: MOV EDX,OFFSET LA
   CALL WRITESTRING
   JMP FIN
 
   ; En este bloque lo que hacemos es ver si lo leído es la letra A
   LE2: MOV EDX,OFFSET LE1
   CALL CRLF
   CALL WRITESTRING
   JMP FIN
 
   LI1: MOV EDX,OFFSET LI
   CALL CRLF
   CALL WRITESTRING
   JMP FIN
 
   LO1: MOV EDX,OFFSET LO
   CALL CRLF
   CALL WRITESTRING
   JMP FIN
 
   LU1: MOV EDX,OFFSET LU
   CALL CRLF
   CALL WRITESTRING
 
   FIN: EXIT
VOCAL ENDP
      END VOCAL
